"""Display labels and accepted synonym groups for Phase 4 text/keyword grading.

Each canonical keyword (stored in correct_answer_raw) maps to:
- LABELS: student-friendly phrase shown under Show Answer
- ALIASES: extra words/phrases that count as a match (UK/US spellings, plurals
  handled separately in answer_checkers inflection logic)
"""

TEXT_KEYWORD_LABELS = {
    'malicious': 'malicious / harmful software',
    'software': 'software / programs',
    'trick': 'trick / deceive / fake',
    'password': 'passwords / credentials',
    'filter': 'filter / block / monitor',
    'traffic': 'network traffic / connections',
    'scan': 'scanning / detecting threats',
    'malware': 'malware / viruses / threats',
    'long': 'long length',
    'unique': 'unique (not reused)',
    'symbol': 'symbols / mixed characters',
    'manipulating': 'manipulating / tricking people',
    'people': 'people / users / humans',
    'encrypt': 'encryption / scrambling data',
    'payment': 'payment / ransom',
    'lock': 'locked doors / physical access control',
    'visitor': 'visitor log / sign-in book',
    'cable': 'cable locks / securing hardware',
    'usb': 'USB access control / no unauthorised devices',
    'pollution': 'manufacturing pollution / toxic waste',
    'mining': 'mining rare earth metals',
    'carbon': 'carbon footprint / emissions',
    'power': 'lower power use / battery life',
    'size': 'smaller size / compact hardware',
    'trolley': 'trolley problem / programmed choices',
    'jobs': 'job losses / unemployment',
    'safety': 'safety vs adoption speed',
    'cctv': 'CCTV / cameras',
    'vulnerabilit': 'security vulnerabilities / flaws',
    'fix': 'fix / patch / update',
    'legitimate': 'legitimate / disguised as safe',
    'replicate': 'self-replicate / spread (without user action for worms)',
    'access': 'access / availability',
    'combinations': 'many password guesses / combinations',
    'two': 'two / second factor',
    'factor': 'factor / type of evidence',
    'same': 'same / shared secret',
    'key': 'key / secret key',
    'public': 'public key',
    'private': 'private key',
    'sql': 'SQL / database queries',
    'database': 'database',
    'authentication': 'authentication (who you are)',
    'authorisation': 'authorisation (what you can access)',
    'relay': 'relay / intercept communications',
    'communication': 'communications / messages',
    'rules': 'rules / acceptable use policy',
    'misuse': 'misuse / inappropriate use',
    'full': 'full backup (everything)',
    'incremental': 'incremental backup (changes only)',
    'permission': 'permission / authorised testing',
    'weakness': 'weaknesses / security flaws',
    'script': 'malicious scripts / code injection',
    'web': 'web pages / websites',
    'transit': 'in transit / while being sent',
    'inside': 'insider / inside the organisation',
    'organisation': 'organisation / company / staff',
    'spoof': 'spoof / fake addresses',
    'mac': 'MAC address',
    'likelihood': 'likelihood / probability',
    'impact': 'impact / severity',
    'network': 'network (automatic spread for worms)',
    'user': 'user action / host file (for viruses)',
    'personal': 'personal data',
    'data': 'data / information',
    'creative': 'creative work',
    'copy': 'copying / copyright',
    'unauthorised': 'unauthorised / without permission',
    'source code': 'source code',
    'licence': 'licence / license',
    'divide': 'digital divide / unequal access',
    'discarded': 'discarded / thrown away electronics',
    'electronic': 'electronic equipment',
    'consent': 'consent / agreement',
    'agree': 'agree / know what is collected',
    'legal': 'legal (breaks the law)',
    'ethical': 'ethical / moral',
    'copyright': 'copyright',
    'outdated': 'outdated / obsolete quickly',
    'waste': 'e-waste / waste',
    'patent': 'patent (inventions)',
    'trademark': 'trademark (brands/logos)',
    'regulator': 'regulator / ICO',
    'authorised': 'authorised / with permission',
    'electricity': 'electricity / energy use',
    'energy': 'energy use / power consumption',
    'erasure': 'right to erasure / deletion',
    'deletion': 'deletion / erase data',
    'attribution': 'attribution / credit the creator',
    'unfair': 'unfair outcomes',
    'bias': 'bias / discrimination',
    'liable': 'liability / who is responsible',
    'crash': 'crash / accident',
    'calculations': 'calculations / arithmetic',
    'logic': 'logic / logical operations',
    'controls': 'controls / coordinates',
    'coordinates': 'coordinates operations',
    'ram': 'RAM / volatile memory',
    'bios': 'BIOS / UEFI',
    'firmware': 'firmware',
    'fetch': 'fetch',
    'decode': 'decode',
    'execute': 'execute',
    'register': 'register(s)',
    'cpu': 'CPU',
    'manages': 'manages / controls resources',
    'resources': 'hardware and software resources',
    'input': 'input device',
    'ssd': 'SSD / solid state',
    'stored program': 'stored program concept',
    'bottleneck': 'Von Neumann bottleneck',
    'frequently': 'frequently used data',
    'faster': 'faster than RAM',
    'secondary': 'secondary storage',
    'storage': 'storage',
    'memory': 'memory',
    'allocates': 'allocates / assigns',
    'process': 'processes / programs',
    'schedules': 'schedules / manages running programs',
    'file': 'files / folders',
    'organises': 'organises / manages',
    'security': 'security / accounts',
    'accounts': 'user accounts / permissions',
    'durable': 'durable / no moving parts',
    'cores': 'cores / multiple cores',
    'multitasking': 'multitasking / parallel programs',
    'instruction': 'instruction fetched from memory',
    'application': 'application software',
    'non-volatile': 'non-volatile',
    'cost': 'lower cost',
    'reliable': 'reliable / dedicated purpose',
    'read only': 'read-only media',
    'portable': 'portable distribution',
    'heat': 'heat / overheating',
    'cooling': 'cooling / heat management',
    'time slicing': 'time slicing / switching between processes',
    'mechanical': 'mechanical parts (HDD)',
    'wear': 'wear on flash / SSD',
    'post': 'POST (power-on self-test)',
    'boot': 'boot / start the OS',
    'address': 'memory address',
    'control': 'control signals',
    'signals': 'signals / read-write commands',
    'parallel': 'parallel / multiple cores',
    'sequential': 'sequential parts of a program',
    'free': 'free / no licence fee',
    'support': 'support / vendor contract',
    'convenient': 'convenient / easy to use',
    'fingerprint': 'fingerprint / biometric risk',
    'shoulder surfing': 'shoulder surfing',
    '2fa': 'two-factor authentication (2FA)',
    'privacy': 'privacy screen / shield keyboard',
    'fdw': 'FDW',
    'data protection': 'data protection / GDPR',
}

TEXT_KEYWORD_ALIASES = {
    'malicious': ('malware', 'harm', 'damage', 'disrupt', 'unauthorised access'),
    'software': ('program', 'programs', 'application', 'applications'),
    'trick': ('trick', 'deceive', 'deceives', 'fake', 'fraud', 'phish', 'misleading'),
    'password': ('password', 'passwords', 'credential', 'credentials', 'login', 'passphrase'),
    'filter': ('filter', 'filters', 'block', 'blocks', 'monitor', 'monitors', 'firewall'),
    'traffic': ('traffic', 'network', 'connections', 'packets'),
    'scan': ('scan', 'scans', 'scanning', 'detect', 'detects', 'checking', 'checks', 'searches'),
    'malware': ('malware', 'virus', 'viruses', 'threat', 'threats', 'trojan', 'ransomware', 'malicious'),
    'long': ('long', 'length', 'lengthy', 'characters', 'character'),
    'unique': ('unique', 'different', 'separate', 'distinct'),
    'symbol': ('symbol', 'symbols', 'uppercase', 'lowercase', 'special character', 'numbers'),
    'manipulating': ('manipulating', 'manipulate', 'trick', 'tricking', 'deceive', 'social engineering'),
    'people': ('people', 'person', 'users', 'user', 'human', 'humans', 'staff', 'employee'),
    'encrypt': ('encrypt', 'encrypts', 'encryption', 'encrypted', 'scramble', 'scrambles', 'locked'),
    'payment': ('payment', 'pay', 'ransom', 'money', 'decryption key'),
    'lock': ('lock', 'locked', 'door', 'doors', 'secure', 'access control', 'keypad', 'badge'),
    'visitor': ('visitor', 'visitors', 'sign in', 'sign-in', 'signin', 'log book', 'logbook', 'register'),
    'cable': ('cable', 'cables', 'cable lock', 'kensington', 'secure hardware'),
    'usb': ('usb', 'flash drive', 'memory stick', 'removable media', 'unauthorised usb', 'unauthorized usb', 'port control'),
    'pollution': ('pollution', 'pollute', 'polluting', 'manufacturing', 'toxic', 'emissions from factory'),
    'mining': ('mining', 'rare earth', 'minerals', 'extract'),
    'carbon': ('carbon', 'footprint', 'emissions', 'co2', 'greenhouse', 'climate'),
    'power': ('power', 'battery', 'batteries', 'energy efficient', 'low power', 'less power'),
    'size': ('size', 'small', 'compact', 'smaller', 'miniature'),
    'trolley': ('trolley', 'moral dilemma', 'ethical choice', 'programmed', 'who to save'),
    'jobs': ('jobs', 'job losses', 'unemployment', 'drivers', 'displacement'),
    'safety': ('safety', 'adoption', 'trust', 'testing', 'risk on roads'),
    'cctv': ('cctv', 'camera', 'cameras', 'surveillance'),
    'vulnerabilit': ('vulnerabilit', 'vulnerability', 'vulnerabilities', 'flaw', 'flaws', 'exploit', 'exploits', 'zero day', 'zero-day'),
    'fix': ('fix', 'fixes', 'patch', 'patches', 'update', 'updates', 'security update'),
    'legitimate': ('legitimate', 'legal', 'pretend', 'pretends', 'disguise', 'disguised'),
    'replicate': ('replicate', 'replicates', 'replicating', 'spread', 'spreads', 'copy', 'copies', 'self replicate'),
    'access': ('access', 'available', 'availability', 'reach', 'use the service'),
    'combinations': ('combinations', 'guesses', 'attempts', 'trial', 'brute force', 'automated'),
    'two': ('two', '2', 'second', 'multi factor', 'multifactor', 'different types'),
    'factor': ('factor', 'factors', 'evidence', 'authentication', 'phone', 'fingerprint', 'biometric'),
    'same': ('same', 'shared', 'one', 'single'),
    'key': ('key', 'keys', 'secret', 'encryption key', 'decryption key'),
    'public': ('public', 'shared openly', 'available', 'openly', 'view', 'modify', 'open source'),
    'private': ('private', 'secret', 'decrypt'),
    'sql': ('sql', 'injection', 'query', 'queries', 'database query'),
    'database': ('database', 'db', 'data store', 'tables'),
    'authentication': ('authentication', 'auth', 'identity', 'login', 'log in', 'who you are', 'prove who'),
    'authorisation': ('authorisation', 'authorization', 'permission', 'permissions', 'access rights', 'allowed', 'what you can'),
    'relay': ('relay', 'relays', 'intercept', 'intercepts', 'middle', 'alter', 'alters', 'eavesdrop'),
    'communication': ('communication', 'communications', 'messages', 'message', 'data sent'),
    'rules': ('rules', 'rule', 'policy', 'policies', 'acceptable use', 'aup'),
    'misuse': ('misuse', 'inappropriate', 'illegal content', 'breaking rules'),
    'full': ('full', 'everything', 'complete', 'all data', 'all files'),
    'incremental': ('incremental', 'changes', 'changed', 'since last backup', 'delta'),
    'permission': ('permission', 'permitted', 'authorised', 'authorized', 'consent', 'legal', 'ethical'),
    'weakness': ('weakness', 'weaknesses', 'vulnerability', 'vulnerabilities', 'flaw', 'flaws', 'exploit'),
    'script': ('script', 'scripts', 'inject', 'injection', 'javascript', 'code'),
    'web': ('web', 'website', 'websites', 'page', 'pages', 'browser', 'html'),
    'transit': ('transit', 'transfer', 'travel', 'sent', 'sending', 'in motion', 'between browser and server'),
    'inside': ('inside', 'internal', 'insider', 'within', 'employee', 'staff'),
    'organisation': ('organisation', 'organization', 'company', 'business', 'school', 'employer'),
    'spoof': ('spoof', 'spoofed', 'spoofing', 'fake', 'forged', 'forge'),
    'mac': ('mac', 'media access control'),
    'likelihood': ('likelihood', 'likely', 'probability', 'chance', 'risk'),
    'impact': ('impact', 'severity', 'consequence', 'consequences', 'damage', 'harm'),
    'network': ('network', 'networks', 'automatically', 'self propagate', 'without user'),
    'user': ('user', 'users', 'action', 'run', 'open', 'host file', 'attach'),
    'personal': ('personal', 'identifiable', 'individual'),
    'data': ('data', 'information', 'details'),
    'creative': ('creative', 'copyright', 'original work', 'work'),
    'copy': ('copy', 'copying', 'copies', 'distribution', 'copyright'),
    'unauthorised': ('unauthorised', 'unauthorized', 'without permission', 'without authorisation', 'illegal access'),
    'source code': ('source code', 'source', 'code available', 'open source'),
    'licence': ('licence', 'license', 'licensing', 'terms'),
    'divide': ('divide', 'gap', 'inequality', 'unequal', 'access'),
    'discarded': ('discarded', 'discarded electronic', 'thrown away', 'disposed'),
    'electronic': ('electronic', 'electrical', 'devices', 'equipment'),
    'consent': ('consent', 'permission', 'agree', 'opt in', 'opt-in'),
    'agree': ('agree', 'consent', 'know', 'informed', 'permission'),
    'legal': ('legal', 'law', 'illegal', 'court', 'prosecution', 'act'),
    'ethical': ('ethical', 'ethics', 'moral', 'morals', 'unfair', 'wrong'),
    'copyright': ('copyright', 'copyright act', 'intellectual property'),
    'outdated': ('outdated', 'obsolete', 'old', 'replace', 'replacement'),
    'waste': ('waste', 'e-waste', 'ewaste', 'e waste', 'landfill'),
    'patent': ('patent', 'patents', 'invention', 'inventions'),
    'trademark': ('trademark', 'trade mark', 'brand', 'logo', 'slogan'),
    'regulator': ('regulator', 'ico', 'information commissioner', 'enforces', 'investigates'),
    'authorised': ('authorised', 'authorized', 'permission', 'with consent', 'legal testing'),
    'electricity': ('electricity', 'electric', 'energy', 'power', 'carbon'),
    'energy': ('energy', 'electricity', 'power', 'consumption', 'carbon', 'data centre', 'datacenter'),
    'cooling': ('cooling', 'cool', 'cooled', 'air conditioning', 'water', 'fan', 'heat sink'),
    'erasure': ('erasure', 'delete', 'deletion', 'right to be forgotten', 'remove data'),
    'deletion': ('deletion', 'delete', 'deletes', 'removed', 'erase'),
    'attribution': ('attribution', 'credit', 'creator', 'author', 'cite'),
    'unfair': ('unfair', 'bias', 'biased', 'discriminat', 'inequal'),
    'bias': ('bias', 'biased', 'unfair', 'discriminat', 'training data'),
    'liable': ('liable', 'liability', 'responsible', 'responsibility', 'blame'),
    'crash': ('crash', 'accident', 'collision', 'crashes'),
    'calculations': ('calculations', 'calculate', 'arithmetic', 'add', 'subtract', 'math'),
    'logic': ('logic', 'logical', 'and', 'or', 'compare', 'comparison'),
    'controls': ('controls', 'control', 'coordinates', 'coordinate', 'manages'),
    'coordinates': ('coordinates', 'coordinate', 'controls', 'fetch-decode-execute'),
    'ram': ('ram', 'random access memory', 'volatile', 'working memory'),
    'bios': ('bios', 'uefi', 'firmware'),
    'firmware': ('firmware', 'bios', 'uefi', 'bootstrap'),
    'fetch': ('fetch', 'fetches', 'fetching'),
    'decode': ('decode', 'decodes', 'decoding', 'interpret'),
    'execute': ('execute', 'executes', 'executing', 'runs', 'run'),
    'register': ('register', 'registers'),
    'cpu': ('cpu', 'processor', 'central processing unit'),
    'manages': ('manages', 'manage', 'managing', 'controls', 'control', 'coordinates'),
    'resources': ('resources', 'hardware', 'software', 'memory', 'processes', 'files'),
    'input': ('input', 'inputs'),
    'ssd': ('ssd', 'solid state', 'solid-state', 'flash memory', 'flash'),
    'stored program': ('stored program', 'programs and data', 'same memory'),
    'bottleneck': ('bottleneck', 'von neumann', 'same bus', 'cannot fetch'),
    'frequently': ('frequently', 'frequent', 'often', 'commonly', 'used often'),
    'faster': ('faster', 'fast', 'speed', 'quicker', 'quick'),
    'secondary': ('secondary', 'long term', 'long-term', 'persistent'),
    'storage': ('storage', 'store', 'stored', 'disk', 'drive'),
    'memory': ('memory', 'ram', 'address', 'location'),
    'allocates': ('allocates', 'allocate', 'assigns', 'assign', 'frees'),
    'process': ('process', 'processes', 'program', 'programs', 'task', 'tasks'),
    'schedules': ('schedules', 'schedule', 'scheduling', 'switches', 'time slice'),
    'file': ('file', 'files', 'folder', 'folders', 'directory'),
    'organises': ('organises', 'organize', 'organizes', 'organising', 'organizing', 'manages'),
    'security': ('security', 'secure', 'accounts', 'permissions', 'malware'),
    'accounts': ('accounts', 'account', 'users', 'permissions', 'login'),
    'durable': ('durable', 'durability', 'moving parts', 'no moving parts', 'shock'),
    'cores': ('cores', 'core', 'multicore', 'multi-core', 'multiple cores'),
    'multitasking': ('multitasking', 'multi tasking', 'parallel', 'many programs', 'at once'),
    'instruction': ('instruction', 'instructions', 'copied from memory', 'fetched'),
    'application': ('application', 'applications', 'app', 'apps', 'word', 'spreadsheet'),
    'non-volatile': ('non-volatile', 'non volatile', 'retained', 'keeps data', 'without power'),
    'cost': ('cost', 'costs', 'cheap', 'cheaper', 'inexpensive', 'power'),
    'reliable': ('reliable', 'reliability', 'dedicated', 'single purpose', 'purpose built'),
    'read only': ('read only', 'readonly', 'read-only', 'distribution', 'films', 'installers'),
    'portable': ('portable', 'portability', 'disc', 'dvd', 'blu-ray'),
    'heat': ('heat', 'hot', 'overheat', 'overheating', 'temperature'),
    'time slicing': ('time slicing', 'time-slicing', 'time slice', 'switches', 'scheduler', 'rotates'),
    'mechanical': ('mechanical', 'moving', 'spinning', 'platters', 'head'),
    'wear': ('wear', 'wears', 'wearing', 'flash cells', 'lifespan'),
    'post': ('post', 'power on self test', 'self-test', 'self test'),
    'boot': ('boot', 'boots', 'booting', 'start', 'starts', 'load os', 'operating system'),
    'address': ('address', 'addresses', 'location', 'memory location'),
    'control': ('control', 'controls', 'read', 'write', 'interrupt', 'clock'),
    'signals': ('signals', 'signal', 'timing', 'commands'),
    'parallel': ('parallel', 'parallelism', 'multiple cores', 'simultaneous'),
    'sequential': ('sequential', 'sequence', 'one after another', 'cannot split', 'single thread'),
    'free': ('free', 'no cost', 'no licence fee', 'no license fee', 'gratis'),
    'support': ('support', 'vendor', 'contract', 'technical staff', 'community'),
    'convenient': ('convenient', 'convenience', 'easy', 'quick', 'hard to guess'),
    'fingerprint': ('fingerprint', 'biometric', 'stolen', 'template', 'cannot change'),
    'shoulder surfing': ('shoulder surfing', 'shoulder-surfing', 'watching', 'observed', 'observation'),
    '2fa': ('2fa', 'two factor', 'two-factor', 'mfa', 'multi factor', 'authenticator'),
    'privacy': ('privacy', 'privacy screen', 'shield', 'shield keyboard', 'third party', 'third-party', 'jurisdiction'),
    'data protection': ('data protection', 'gdpr', 'dpa', 'personal data', 'data law', 'privacy law'),
}


def text_keyword_labels(keywords):
    """Human-readable labels for Show Answer (falls back to title-cased keyword)."""
    out = []
    for kw in keywords:
        key = str(kw).strip().lower()
        out.append(TEXT_KEYWORD_LABELS.get(key, key.replace('|', ' / ')))
    return out


def text_keyword_aliases(keyword):
    """All match strings for one canonical keyword."""
    key = str(keyword).strip().lower()
    aliases = {key}
    aliases.update(TEXT_KEYWORD_ALIASES.get(key, ()))
    return aliases
